context.properties = {
}

context.spa-libs = {
  support.* = support/libspa-support
}

context.objects = [
  { factory = spa-node-factory
    args = {
      factory.name    = support.node.driver
      node.name       = sysclk-driver
      node.group      = pipewire.sysclk
      node.sync-group = sync.sysclk
      priority.driver = 0
      clock.name      = realtime
      clock.id        = realtime
      object.export   = true
    }     
  }
]

context.modules = [
    { name = libpipewire-module-rt
        args = {
            nice.level   = -11
            #rt.prio      = 83
            #rt.time.soft = -1
            #rt.time.hard = -1
        }
        flags = [ ifexists nofail ]
    }
  { name = libpipewire-module-protocol-native }
  { name = libpipewire-module-client-node }
  { name = libpipewire-module-spa-node-factory }
  { name = libpipewire-module-adapter }
  { name = libpipewire-module-loopback
    args = {
      capture.props = {
        node.name        = speakers
        node.description = Speakers
        media.class      = Audio/Sink
        audio.position   = [FL FR]
      }
      playback.props = {
        media.class       = Stream/Output/Audio
        stream.dont-remix = true
        target.object     = alsa_output.usb-Focusrite_Scarlett_4i4_4th_Gen_S4Q366K3700949-00.pro-output-0
        audio.position    = [AUX0 AUX1]
      }
    }
  }
  { name = libpipewire-module-loopback
    args = {
      capture.props = {
        node.name        = headphones
        node.description = Headphones
        media.class      = Audio/Sink
        audio.position   = [FL FR]
      }
      playback.props = {
        media.class       = Stream/Output/Audio
        stream.dont-remix = true
        target.object     = alsa_output.usb-Focusrite_Scarlett_4i4_4th_Gen_S4Q366K3700949-00.pro-output-0
        audio.position    = [AUX2 AUX3]
      }
    }
  }
]
