context.properties = {
}

context.spa-libs = {
  support.* = support/libspa-support
}

context.objects = [
  { factory = spa-node-factory
    args = {
      factory.name    = support.node.driver
      node.name       = sysclk-driver
      node.group      = pipewire.sysclk
      node.sync-group = sync.sysclk
      priority.driver = 0
      clock.name      = realtime
      clock.id        = realtime
      object.export   = true
    }     
  }
]

context.modules = [
    { name = libpipewire-module-rt
        args = {
            nice.level   = -11
            #rt.prio      = 83
            #rt.time.soft = -1
            #rt.time.hard = -1
        }
        flags = [ ifexists nofail ]
    }
  { name = libpipewire-module-protocol-native }
  { name = libpipewire-module-client-node }
  { name = libpipewire-module-spa-node-factory }
  { name = libpipewire-module-adapter }
  { name = libpipewire-module-filter-chain
    args = {
      filter.graph = {
        nodes = [
          { type = builtin, label = copy, name = in }
          { type = builtin, label = copy, name = L  }
          { type = builtin, label = copy, name = R  }
        ]
        links   = [
          { output = "in:Out", input = "L:In" }
          { output = "in:Out", input = "R:In" }
        ]
        inputs  = ["in:In"]
        outputs = ["L:Out", "R:Out"]
      }
      capture.props  = { 
        target.object    = alsa_input.usb-Focusrite_Scarlett_4i4_4th_Gen_S4Q366K3700949-00.pro-input-0
        media.class      = Stream/Input/Audio
        audio.position   = [AUX0]
      }
      playback.props = { 
        node.name         = headset-mic
        node.description  = "Headset Microphone"
        media.class       = Audio/Source
        stream.dont-remix = true
        audio.position    = [FL FR]
      }
    }
  }
]
