vim.api.nvim_set_option("expandtab", true)
vim.api.nvim_set_option("smarttab", true)
vim.api.nvim_set_option("tabstop", 2)
vim.api.nvim_set_option("softtabstop", 2)
vim.api.nvim_set_option("shiftwidth", 2)
