# vim ft=hypr

wallpaper {
    monitor = DP-1
    path = ~/.local/share/wallpapers/chongqing.jpg
}
wallpaper {
    monitor = DP-5
    path = ~/.local/share/wallpapers/chongqing.jpg
}
wallpaper {
    monitor = DP-8
    path = ~/.local/share/wallpapers/chongqing.jpg
}
splash = false
