# vim: ft=hyprlang

monitor = desc:Dell Inc. DELL U2421E JD77DH3, preferred, 1920x0, 1
monitor = desc:Dell Inc. DELL U2421E 5PCGK04, preferred, 0x0, 1
monitor = desc:Dell Inc. DELL U2715H GH85D54B00HL, preferred, 0x0, 1
monitor = desc:Dell Inc. DELL U2421E 6ZC7DH3, preferred, 2560x0, 1
#monitor = ,preferred,auto,1
